= Asciidoc

:encoding: utf-8
:lang: de
:keywords: ascii, asciidoc, 
:revision: 0.0.1
:revnumber:
:revdate: 
:revremark: 
:copyright: me me and only me
:author: fs
:email: fs@example.com
:toc:
:toc-title: asciidoc
 
Copyright: {copyright} +
Author: {author} +
eMail: {email} +
Version: {revision} +
// vim set: syntax=asciidoc
 
toc::[]



== Was ist Asciidoc
AsciiDoc ist eine vereinfachte Auszeichnungssprache, die dazu dient, Texte in verschiedenen Dokumentenformaten zu veröffentlichen. Zum beispiel: HTML,pdf,Epub.

== Wie installiere ich Asciidoc

[source,bash]
.Zu allererst muss ich zum Root werden
----
sudo -iu root
----

[source,bash]
.und kann danach asciidoc installieren
----
 apt-get install asciidoc
----

Asciidoctor erzeugt seine dateien im *.adoc* Format. Dieses Format eignet sich hervorragend um damit Man-Pages oder auch HTML-Dateien zu erstellen.


== Verschiedene Überschriften

Um verschiedene Überschriften zu erstellen, damit man im Text eine Struktur der Form bekommt, kann man mit unterschiedlichen Anzahlen des Zeichens *=* arbeiten. So wird die Hauptüberschrift mit einem einzelnen *=* gekennzeichnet und alle darauffolgenden Unterüberschriften um jeweils ein *=* ergänzt

= Hauptüberschrift des Textes

----
= Hauptüberschrift des Textes
----

== Überschrift H1

----
== Überschrift H1
----

=== Überschrift H2

----
=== Überschrift H2
----

==== Überschrift H3

----
==== Überschrift H3
----




== Schriftarten

[source,bash]
.Schriftarten können ganz einfach mit Sonderzeichen geändert werden.

----
*Text fettgedruckt*
----

----
_Text kursiv_
----

----
`Text mono`
----

== Beschreibungen und Anmerkungen

[source,bash]
.Für Beschreibungen, z.B. eines Befehles nutzt man den Ausdruck *[source,bash]* :

----
[source,bash]
.
----

Dabei ist zu beachten, dass die Beschreibungen direkt nach dem *.* in der zweiten Zeile schreibt


=== Tabellen

==== Als Beispiel Personen

[source,bash]
.Für Tabellen nutzt man entweder den unten stehenden Befehl, oder man kopiert einfach die Tabelle aus http://asciiflow.com/

----
[width="60%",cols="<50,<30,>20",options="header,footer"]
|===
|Name
|Geburtsdatum
|Schuhgroesse

|Peter
|20.02.1980
|45

|Ute
|01.05.1976
|38

|===
----

[source,bash]
.In der Ausgabe erscheint dann :

[width="60%",cols="<50,<30,>20",options="header,footer"]
|===
|Name
|Geburtsdatum
|Schuhgroesse

|Peter
|20.02.1980
|45
 
|Ute
|01.05.1976
|38
 
|===

Durch Verändern der Zahlenwerte in den []-Klammern können als Beispiel Breite und Höhe der Tabelle angepasst werden.


== Diagramme

[source,bash]
.Um Diagramme erstellen zu können und sie im asciidoctor zu nutzen,benötigt es die vorhergehende zeile *[ditaa]*.

----
[ditaa] 
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
....

----


In der Ausgabe erscheint das Diagramm dann so:

[ditaa]
....
                   +-------------+                                                                      
                   | Asciidoctor |-------+                                                              
                   |   diagram   |       |                                                              
                   +-------------+       | PNG out                                                      
                       ^                 |                                                              
                       | ditaa in        |                                                              
                       |                 v                                                              
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |                                                      
 |  Text  |   +-------------+    |   Beautiful   |                                                      
 |Document|   |   !magic!   |    |    Output     |                                                      
 |     {d}|   |             |    |               |                                                      
 +---+----+   +-------------+    \---------------/                                              
....





Grafiken, Tabellen und Ähnliches können entweder mühsam per Hand, oder einfacher durch die unten stehenden Links erzeugt, kopiert und eingefügt werden.

http://stable.ascii-flow.appspot.com/#Draw

http://asciiflow.com/


== Listen

Um Listen zu erstellen verwenden wir die Zeichen * und .

----
==== Autos

* Audi
* Tesla
* Mosler

----

----
=== Motorräder

. Honda
.. Kawasaki
... Suzuki
. Harley Davidson
. Kreidler

----



In der Ausgabe wird dann folgendes erscheinen:

==== Autos

* Audi
* Tesla
* Mosler

=== Motorräder

. Honda
.. Kawasaki
... Suzuki
. Harley Davidson
. Kreidler



== Checkboxen

Checkboxen können wir wie folgt erstellen:

----
* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item
----


Die Ausgabe sieht dann so aus:


* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item





=== PDF Erstellung durch Ascii

[source,bash]
.Asciidoctor kann mit vielen verschiedenen Features ausgestattert werden.Diese Features sind vielseitig einsetzbar.In unserem Fall ist es asciidoctor-PDF. Wir erzeugen dabei eine Datei im *.pdf* Format.

*beispiel.pdf*

[source,bash]
.Möchte man jetzt diese Datei in ein PDF ausgeben lassen, so nutzt man den Befehl:

----
asciidoctor-pdf beispiel.adoc
----

[source,bash]
.Durch diesen Befehl wird die *.adoc* Datei in eine *.pdf* datei umgewandelt.In unserem Ordner _/home/desktop/_ befinden sich nun 2 Dateien.

`beispiel.adoc` & `beispiel.pdf`

Beide Dateien haben nun den selben Inhalt, aber sind in einem unterschiedlichen Dateiformat. Die *.adoc* Datei kann aber im Gegensatz zu der *.pdf* Datei aber immer erweitert und verändert werden.



