= Bash

== _Einfuehrung_

Laut Wikipedia:
Bash (auch BASH oder bash), die Bourne-again shell, ist eine freie Unix-Shell unter GPL. +

Als Shell ist Bash eine Mensch-Maschine-Schnittstelle, die eine Umgebung (englisch environment) bereitstellt, in der zeilenweise Texteingaben und -ausgaben möglich sind. Letzteres erfolgt über die Befehlszeile, in die Befehle eingetippt und durch betätigen der Eingabetaste eingegeben werden. 

Bash-Skripte sind geeignet um Programme, gemäß der eigenen Bedürfnisse, miteinander zu kombinieren und sie spielen eine zentrale Rolle im Alltag der Systemadministration.


== _Installation/Setup_ +
Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
es wird keine installation benötigt abgesehen von der installation von Linux betriebssystem

== _Vorbereitung_
Für die Bash wird keine weitere Vorbereitung benötigt, da es eine vorinstallierte Anwendung ist. +

== _Anwendung_
Man nutz die shell für ausführungen von Befehlen direkt aus der Shell heraus
innerhalb der shell kann man sich per befhle in den verzeichnissen bewegen. +
[source,bash]
.um innerhalb seines verzeichnis ein neues verzeichnis zu erstellen benötigt man den befehl:
----
mkdir (verzeichnisname)
----
-> der Befehl bedeutet _make directory_ also _ein Verzeichnis erstellen_.
Benutzen wir diesen Befehl aus dem Grundverzeichnis heraus _/home/benutzer_ wird dort ein Ordner angelegt.
 
 
-> Um jetzt in den angelegten Ordner zu wechseln
[source,bash]
.gibt man den Befehl ein
----
cd (Ordnername)
----
-> In diesem befehl __cd__ stecken die worte 'change' und 'directory'

[source,bash]
.Beispiel: befinden wir uns im grundverzeichnis: /home/benutzer/ können wir mit dem befehl
----
cd /home/benutzer/XYZ
----
unser aktuellen standort auf das verzeichnis 'XYZ'

[source,bash]
.Um nun Herauszufinden in welchen Verzeichnis wir uns befinden: 'Public Works Department'
----
pwd
----
nun wird angezeigt in welchem Verzeichnis wir uns befinden.

*/home/benutzer/XYZ$*

[source,bash]
.Den aktuellen ordnerinhalt lässt sich anzeigen mit dem befehl:
----
ls -la
----
steht in dem falle das __ls__ für 'listing' also auflisten,
die option __-la__ steht hierbei für 'long all' also lange, ausführliche liste.


[source,bash]
.die auflistung in voller Ausführung befielt man mit
----
ls -la /home/benutzer
----

[source,bash]
.um eine Datei in diesem Verzeichnis zu erstellen
----
oasis.txt
----
Somit wird eine Textdatei angelegt mit dem namen 'oasis'

=== Formatierung
Es handelt sich um eine shell sodass eine Formatierung nicht vorhanden ist

=== Ausgabe
Die ausgabe findet ausschliesslich in textbasierter ausgabe in der shell statt

