= Bash

== Einfuehrung

Laut Wikipedia:
Bash (auch BASH oder bash), die Bourne-again shell, ist eine freie Unix-Shell unter GPL.

Als Shell ist Bash eine Mensch-Maschine-Schnittstelle, die eine Umgebung (englisch environment) bereitstellt, in der zeilenweise Texteingaben und -ausgaben möglich sind. Letzteres erfolgt über die Befehlszeile, in die Befehle eingetippt und durch betätigen der Eingabetaste eingegeben werden. 

Bash-Skripte sind geeignet um Programme, gemäß der eigenen Bedürfnisse, miteinander zu kombinieren und sie spielen eine zentrale Rolle im Alltag der Systemadministration.


<<<<<<< HEAD

== Installation/Setup

=======
== Installation/Setup
>>>>>>> 067566a4c6812fe4f65d45bcbbeee2bd8ec08ca5
Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
es wird keine Installation benötigt.

== Vorbereitung
<<<<<<< HEAD

Für die Bash wird keine weitere Vorbereitung benötigt. Da es eine vorinstallierte Anwendung ist.

== Anwendung
Man nutzt die Shell für die Ausführung von Befehlen.
=======
Für die Bash wird keine weitere Vorbereitung benötigt. Da es eine vorinstallierte Anwendung ist.

== Anwendung
Man nutzt die Shell für die Ausführung von Befehlen. +
>>>>>>> 067566a4c6812fe4f65d45bcbbeee2bd8ec08ca5
Innerhalb der Shell kann man sich über Befehle in den Verzeichnissen bewegen.


<<<<<<< HEAD
Für die Bash wird keine weitere Vorbereitung benötigt, da es eine vorinstallierte Anwendung ist.

== Anwendung
Man nutz die shell für ausführungen von Befehlen direkt aus der Shell heraus
innerhalb der shell kann man sich per befhle in den verzeichnissen bewegen.
=======
== Anwendung
Man nutz die shell für ausführungen von Befehlen direkt aus der Shell heraus
innerhalb der shell kann man sich per befhle in den verzeichnissen bewegen. +
>>>>>>> 067566a4c6812fe4f65d45bcbbeee2bd8ec08ca5

[source,bash]
.Um innerhalb eines Verzeichnis ein neues Verzeichnis zu erstellen benötigt man den Befehl:
----
mkdir *Verzeichnisname)*
----
<<<<<<< HEAD

-> Der Befehl bedeutet 'make directory' also ein Verzeichnis erstellen.
=======
 Der Befehl bedeutet 'make directory' also ein Verzeichnis erstellen.
=======
>>>>>>> 067566a4c6812fe4f65d45bcbbeee2bd8ec08ca5
-> der Befehl bedeutet _make directory_ also _ein Verzeichnis erstellen_.
Benutzen wir diesen Befehl aus dem Grundverzeichnis heraus _/home/benutzer_ wird dort ein Ordner angelegt.
 
 
-> Um jetzt in den angelegten Ordner zu wechseln
[source,bash]
.Mit dem Befehl:
----
cd *Verzeichnisname*
----
wechselt man aus dem aktuellen Verzeichnis zu einem Ziel Verzeichnis.

->In dem Befehl __cd__ stecken die Worte 'change' und 'directory'








[source,bash]
.Beispiel: befinden wir uns im Grundverzeichnis: /home/Benutzer/ können wir mit dem Befehl
----
cd /home/benutzer/XYZ
----
unser aktuellen Standort auf das Verzeichnis _XYZ_ wechseln.

[source,bash]
.Um herauszufinden in welchem Verzeichnis wir uns befinden, den Befehl _'Public Works Department'_
----
pwd
----
eingegeben und uns wird angezeigt in welchem Verzeichnis wir sind.


[source,bash]
.Der aktuelle Ordnerinhalt lässt sich mit dem Befehl
----
ls -la
----
anzeigen. _ls_ steht hier für 'listing' also auflisten,
die Option _-la_ steht hier für 'long all', also eine lange, ausführliche Liste.


[source,bash]
.Die Auflistung in langer Ausführung zB im _Home_ Verzeichnis bekommt man mit
----
ls -la /home/Benutzer
----


== Formatierung

-> Es handelt sich um eine Shell, sodass eine Formatierung nicht vorhanden ist.

== Ausgabe

-> Die Ausgabe findet ausschliesslich in textbasiert statt.

