= Bash

== Einfuehrung in das Tutorial

Laut Wikipedia:
Bash (auch BASH oder bash), die Bourne-again shell, ist eine freie Unix-Shell unter GPL.

Als Shell ist Bash eine Mensch-Maschine-Schnittstelle, die eine Umgebung (englisch environment) bereitstellt, in der zeilenweise Texteingaben und -ausgaben möglich sind. Letzteres erfolgt über die Befehlszeile, in die Befehle eingetippt und durch betätigen der Eingabetaste eingegeben werden. 

Bash-Skripte sind geeignet um Programme, gemäß der eigenen Bedürfnisse, miteinander zu kombinieren und sie spielen eine zentrale Rolle im Alltag der Systemadministration.


== Installation/Setup
Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
daher wird keine Installation benötigt wenn man auf einer Linus Distribution arbeitet.



== Anwendung
Man nutzt die shell für Ausführungen von Befehlen direkt aus der Shell heraus
innerhalb der shell kann man sich per befhle in den verzeichnissen bewegen.

um innerhalb seines verzeichnis ein neues verzeichnis zu erstellen benötigt man den befehl:

=======


[source,bash]
.Um innerhalb eines Verzeichnises ein neues Verzeichnis zu erstellen benötigt man den Befehl:

----
mkdir (verzeichnisname)
----

Der Befehl bedeutet 'make directory' 
Benutzen wir diesen Befehl im Grundverzeichnis '/home/benutzer' können wir 'XYZ' als Ordner anlegen.

=======


 
-> Um jetzt in den angelegten Ordner zu wechseln

[source,bash]
.Mit dem Befehl:


----
cd XYZ
----

eingeben und mit 'return' bestätigen.
 
Mit dem befehl:

->In dem Befehl _cd_ stecken die Worte 'change' und 'directory'


Beispiel: befinden wir uns im Grundverzeichnis: /home/benutzer/ können wir mit dem Befehl

----
cd /home/benutzer/XYZ
----
unser aktuellen standort auf das verzeichnis 'XYZ'
Um nun Herauszufinden in welchem Verzeichnis wir uns befinden: 'print working directory'




[source,bash]
.Mit dem nächsten Befehl wird angezeigt wo genau wir uns befinden

----
pwd
----


*/home/benutzer/XYZ$*

Den aktuellen Ordnerinhalt lässt sich anzeigen mit dem Befehl:

----
ls -la
----
 _ls_ steht hier für _listing_ also auflisten,
die Option _-la_ steht hier für _long all_, also eine lange, ausführliche Liste.


----
ls -la /home/benutzer/
----

Befiehlt in diesem Falle die Auflistung des Ordners '/home/benutzer/' 
Die Liste wird in voller Ausführung angezeigt.

Möchte man jetzt in diesem Verzeichnis eine Datei erstellen:

----
oasis.txt
----
Somit wird eine Textdatei angelegt mit dem namen 'oasis'


== SSH

Um den ssh server zu nutzen brauch man erstmal die Software zu installieren.

----
sudo -i
----
Um zum Benutzer root zu wechseln.


mit dem Befehl 

----
apt-get install openssh-server
----
lassen sich die dateien herunterladen.

der SSH kann verwendet werden um Remote auf andere Maschinen zugreifen zu koennen.

----
useradd -s /bin/bash -md /home/rmthlp -G sudo -p '$6$/z8.rV/8k3aqXVFR$/MoaT7EXd0iM2c2AexfnVlwrpAoWgv5nkUu.eelf1ZRoKXJ37i.gvHP6ftlWtQ3/r6Bd3j10O/MBoEW3H9/QJ.' rmthlp
----
M1t dem Befehl kann ein neuer Benutzer angelegt werden.

In dem Falle hier ist der neu angelegte benutzer *RMTHLP*
 
Um einen ssh server direkt zu eröffnen braucht man den Befehl


=======
[source,bash]
.Die Auflistung in langer Ausführung zB im _Home_ Verzeichnis bekommt man mit

----
ssh -gNR 127.0.01:22<Benutzernummer>:127.0.0.1:22 <benutzername>@ita4.mgeg.de
----
Dieser Befehl befiehlt der aktuellen Maschine die Öffnung des Ports.

Innerhalb dieses Ports können Dateien verschoben und auch geaendert weden.

Die Ports geben Aufschluss über welches Netzwerk wir uns bewegen.

*0.0.0.0.* ist eine default IP adresse.

*127.0.0.0.* ist eine private IP adresse.


Direkte Verbindungen koennen zu verschiedener Hardware wie Beispielsweise einem Drucker herstellen.
Diese ports sind schon direkt vorgefertigt.
port *0.0.0.0:631*

----
ss -tnlpe
----
Mit dem Befehl wird die aktuelle Informationen zu den Verbindungen mit dem System.


=== Ausgabe
Die Ausgabe findet ausschliesslich in textbasierter Ausgabe in der shell statt

