= Bash

== Einfuehrung in das Tutorial

Laut Wikipedia:
Bash (auch BASH oder bash), die Bourne-again shell, ist eine freie Unix-Shell unter GPL.

Als Shell ist Bash eine Mensch-Maschine-Schnittstelle, die eine Umgebung (englisch environment) bereitstellt, in der zeilenweise Texteingaben und -ausgaben möglich sind. Letzteres erfolgt über die Befehlszeile, in die Befehle eingetippt und durch betätigen der Eingabetaste eingegeben werden. 

Bash-Skripte sind geeignet um Programme, gemäß der eigenen Bedürfnisse, miteinander zu kombinieren und sie spielen eine zentrale Rolle im Alltag der Systemadministration.


== Installation/Setup
Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
daher wird keine Installation benötigt wenn man auf einer Linus Distribution arbeitet.



== Anwendung
Man nutzt die shell für Ausführungen von Befehlen direkt aus der Shell heraus
innerhalb der shell kann man sich per befhle in den verzeichnissen bewegen.

um innerhalb seines verzeichnis ein neues verzeichnis zu erstellen benötigt man den befehl:

=======

== Installation/Setup

Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
es wird keine Installation benötigt.

== Vorbereitung

Für die Bash wird keine weitere Vorbereitung benötigt. Da es eine vorinstallierte Anwendung ist.

== Anwendung
Man nutzt die Shell für die Ausführung von Befehle.
Für die Bash wird keine weitere Vorbereitung benötigt. Da es eine vorinstallierte Anwendung ist.

[source,bash]
.Um innerhalb eines Verzeichnis ein neues Verzeichnis zu erstellen benötigt man den Befehl:
>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8
----
mkdir (verzeichnisname)
----
<<<<<<< HEAD
der befehl bedeutet 'make directory' also ein verzeichnis erstellen.
benutzen wir diesen befehl auf dem grundverzeichnis '/home/benutzer' können wir 'XYZ' als verzeichnis
anlegen indem wir 

=======

-> Der Befehl bedeutet 'make directory' also ein Verzeichnis erstellen.

Benutzen wir diesen Befehl aus dem Grundverzeichnis heraus _/home/benutzer_ wird dort ein Ordner angelegt.
 
 
-> Um jetzt in den angelegten Ordner zu wechseln

[source,bash]
.Mit dem Befehl:

>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8
----
mkdir XYZ
----
eingeben und mit 'return' bestätigen.
 
Mit dem befehl:

<<<<<<< HEAD
=======
->In dem Befehl _cd_ stecken die Worte 'change' und 'directory'
.gibt man den Befehl ein.

>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8
----
cd
----
<<<<<<< HEAD
wechselt man das aktuelle verzeichniss auf ein ziel verzeichnis
in diesem befehl __cd__ stecken die worte 'change' und 'directory'

beispiel: befinden wir uns im grundverzeichnis: /home/benutzer/ können wir mit dem befehl

----
cd /home/benutzer/XYZ
----
unser aktuellen standort auf das verzeichnis 'XYZ'
Um nun Herauszufinden in welchen Verzeichnis wir uns befinden: 'Public Works Department'
=======

-> In diesem befehl _cd_ stecken die worte 'change' und 'directory'

[source,bash]
.Beispiel: befinden wir uns im Grundverzeichnis: /home/Benutzer/ können wir mit dem Befehl

----
cd /home/benutzer/XYZ
----

unser aktuellen Standort auf das Verzeichnis _XYZ_ wechseln.
>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8

----
pwd
----
nun wird angezeigt in welchem verzeichnis wir uns befinden.

*/home/benutzer/XYZ$*

Den aktuellen ordnerinhalt lässt sich anzeigen mit dem befehl:

----
ls -la
----
<<<<<<< HEAD
=======
anzeigen. _ls_ steht hier für _listing_ also auflisten,
die Option _-la_ steht hier für _long all_, also eine lange, ausführliche Liste.
>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8

steht in dem falle das __ls__ für 'listing' also auflisten,
die option __-la__ steht hierbei für 'long all' also lange, ausführliche liste.

----
ls -la /home/benutzer/
----

befielt in diesem falle die auflistung des ordners '/home/benutzer/' 
Die liste wird in voller ausführung angezeigt.

will man jetzt in diesem Verzeichnis eine datei erstellen:

----
oasis.txt
----
Somit wird eine Textdatei angelegt mit dem namen 'oasis'


== SSH

Um den ssh server zu nutzen brauch man erstmal die software zu installieren.

----
sudo -i
----
um zum benutzer root zu wechseln.


mit dem Befehl 

----
apt-get install openssh-server
----
lassen sich die dateien herunterladen.

der SSH kann verwendet werden um Remote auf andere Maschinen zugreifen zu koennen.

----
useradd -s /bin/bash -md /home/rmthlp -G sudo -p '$6$/z8.rV/8k3aqXVFR$/MoaT7EXd0iM2c2AexfnVlwrpAoWgv5nkUu.eelf1ZRoKXJ37i.gvHP6ftlWtQ3/r6Bd3j10O/MBoEW3H9/QJ.' rmthlp
----
mit dem befehl kann ein neuer benutzer angelegt werden.

n dem falle hier ist der neu angelegte benutzer *RMTHLP*
 
um einen ssh server direkt zu eröffnen brauch man den befehl

<<<<<<< HEAD
=======
[source,bash]
.Die Auflistung in langer Ausführung zB im _Home_ Verzeichnis bekommt man mit

>>>>>>> 213a16c1aabc2caf8da38c5b3dcca09a114fafd8
----
ssh -gNR 127.0.01:22<Benutzernummer>:127.0.0.1:22 <benutzername>@ita4.mgeg.de
----
Dieser befehl befielt der aktuellen maschine die öffnung des ports.

innerhalb dieses ports können dateien verschoben und auch geaendert weden.

die ports geben aufschluss über welches netzwerk wir uns bewegen.

*0.0.0.0.* ist eine default IP adresse.

*127.0.0.0.* ist eine private IP adresse.


direkte verbindungen koennen zu verschiedenen Hardware wie beispielsweise einem Drucker herstellen.
diese ports sind schon direkt vorgefertigt.
port *0.0.0.0:631*

----
ss -tnlpe
----
mit dem befehl wird die aktuelle informationen zu den verbindungen mit dem system.

=== Formatierung
Es handelt sich um eine shell sodass eine Formatierung nicht vorhanden ist

=== Ausgabe
Die ausgabe findet ausschliesslich in textbasierter ausgabe in der shell statt

