= Bash

== _Einfuehrung_

Laut wikipedia:
Bash (auch BASH oder bash), die Bourne-again shell, ist eine freie Unix-Shell unter GPL.

Als Shell ist Bash eine Mensch-Maschine-Schnittstelle, die eine Umgebung (englisch environment) bereitstellt, in der zeilenweise Texteingaben und -ausgaben möglich sind. Letzteres erfolgt über die Befehlszeile, in die Befehle eingetippt und durch betätigen der Eingabetaste eingegeben werden. 

Bash-Skripte sind geeignet um Programme, gemäß der eigenen Bedürfnisse, miteinander zu kombinieren und sie spielen eine zentrale Rolle im Alltag der Systemadministration.


== _Installation/Setup_
Die Bash ist eine vorinstallierte Shell auf den meisten GNU/Linux Betriebssystemen
es wird keine installation benötigt.

== _Vorbereitung_
Für die Bash wird keine weitere Vorbereitung benötigt. Da es eine vorinstallierte Anwendung ist.

== _Anwendung_
Man nutzt die Shell für die Ausführung von Befehlen. +
Innerhalb der shell kann man sich über Befehle in den Verzeichnissen bewegen.

[source,bash]
.Um innerhalb seines Verzeichnis ein neues Verzeichnis zu erstellen benötigt man den Befehl:
----
mkdir *Verzeichnisname)*
----
-> Der Befehl bedeutet 'make directory' also ein Verzeichnis erstellen.
 

[source,bash]
.Mit dem Befehl:
----
cd *Verzeichnisname*
----
wechselt man aus dem aktuellen Verzeichnis zu einem Ziel Verzeichnis. +
->In dem Befehl __cd__ stecken die Worte 'change' und 'directory'

[source,bash]
.Beispiel: befinden wir uns im Grundverzeichnis: /home/Benutzer/ können wir mit dem Befehl
----
cd /home/benutzer/XYZ
----
unser aktuellen Standort auf das Verzeichnis _XYZ_ wechseln. +

[source,bash]
.Um herauszufinden in welchem Verzeichnis wir uns befinden, den Befehl _'Public Works Department'_
----
pwd
----
eingegeben und uns wird angezeigt in welchem Verzeichnis wir sind. +


[source,bash]
.Der aktuelle Ordnerinhalt lässt sich mit dem Befehl
----
ls -la
----
anzeigen. _ls_ steht hier für 'listing' also auflisten,
die Option _-la_ steht hier für 'long all', also eine lange, ausführliche Liste.


[source,bash]
.Die Auflistung in langer Ausführung zB im _Home_ Verzeichnis bekommt man mit
----
ls -la /home/Benutzer
----


== _Formatierung_

-> Es handelt sich um eine Shell, sodass eine Formatierung nicht vorhanden ist.

== _Ausgabe_

-> Die Ausgabe findet ausschliesslich in textbasiert statt.

