= PyCharm

PyCharm ist eine intergrierte Entwicklungsumgebung _IDE_ für die Programmiersprache Python.


== Installation

Um PyCharm zu installieren kann man sich entweder auf der Website von _JetBrains_ die passende Version herunterladen oder, sofern Ubunutu als Betriebssystem genutzt wird, PyCharm direkt über den _Ubuntu Store_ installieren.


[source,bash]
.Der Download ist unter folgender URL zu finden
----
https://www.jetbrains.com/de-de/pycharm/download/#section=linux
----
-> es stehen zwei Versionen von PyCharm zum Download. Eine kostenfreie _Community Version_ und eine kostenpflichtige _Professional Version_. 

[source,bash]
.Nach dem download, entpackt man die Archivdatei zunächst und öffnet das Verzeichnis mit dem Befehl
----
cd pycharm-community-2019.3.4/bin
----
-> Hier wurde die Archivdatei in das _Home_ Verzeichnis entpackt.


[source,bash]
.Im Anschluss öffnet man das _Setup_ um PyCharm zu installieren.
----
pycharm.sh
----

[source,bash]
.Auf der unteren rechten Seite, unter _configure_ kann man Auswählen, ob ein Desktop Icon erstellt werden soll.
----
Create desktop entry
----


