= Pycharm

PyCharm ist eine integrierte Entwicklungsumgebung (IDE) für die Programmiersprache Python.

== Installation

Um Pycharm zu installieren kann man sich entweder auf der Internetseite die passende Version herunterladen. Den Downloadlink findet man unter folgendem Link
=======
Um Pycharm zu installieren kann man sich entweder auf der Internetseite, den die passende Version herunterladen. Den Download findet man unter folgendem Link:
>>>>>>> d1ba26cf867c2a67020d2412ce99e4537cc53827

----
https://www.jetbrains.com/de-de/pycharm/download/#section=linux
----

Oder man installiert sich, sofern man eine Ubuntu Distribution besitzt, Pycharm direkt über den Ubuntustore auf seinem System.

Wenn man den Downloadlink benutzt hat man die Auswahl zwischen einer kostenfreien und einer kostenpflichtigen Version. Die kostenlose Version ist die Communityversion.

Wenn man eine Version heruntergeladen hat, entpackt man diese Datei zunächst und öffnet das Verzeichnis mit dem Befehl


[source,bash]

----
cd pycharm-community-2019.3.4/bin
----

[source,bash]
.Im Anschluss öffnet man das Programm um es zu installieren.

----
pycharm.sh
----

* Auf der unteren rechten Seite, unter _configure_ kann man sich ein Desktop Icon erstellenlassen 

----
Create desktop entry
----


