= Pycharm

PyCharm ist eine integrierte Entwicklungsumgebung (IDE) für die Programmiersprache Python.

== Installation

Um Pycharm zu installieren kann man sich entweder auf der Internetseite, den die passende Version herunterladen. Den Downloadlink findet man unter folgendem Link

----
https://www.jetbrains.com/de-de/pycharm/download/#section=linux
----

Oder man installiert sich, sofern man eine Ubuntu Distribution besitzt, Pycharm direkt über den Ubuntustore auf seinem System.

Wenn man den Downloadlink benutzt hat man die Auswahl zwischen einer kostenfreien und einer kostenpflichtigen Version. Die kostenlose Version ist die Communityverion.

Wenn man eine Version heruntergeladen hat, entpackt man diese Datei zunächst und öffnet das Verzeichnis mit dem Befehl


[source,bash]

----
cd pycharm-community-2019.3.4/bin
----

[source,bash]
.Im Anschluss öffnet man das Programm um es zu installieren.

----
pycharm.sh
----

* Auf der unteren rechten Seite, unter configure kann man ein Desktopicon erstellen 

----
Creat desktop entry
----


