= Remotehelp über eine SSH Verbindung

Mittels SSH _Secure Shell_ kann eine verschlüsselte Verbindung zur Kommandozeile _Shell_ des _SSH Servers_ hergestellt werden. So ist es möglich _Remote_ Hilfe zu bekommen, da Befehle von der _Hilfe gebenden_ auf dem System eingegeben werden können.
SSH Clients gint es für quasi alle verwendeten Betriebssysteme, unter Windows 10 ist z.B. ein SSH Client für die Kommandozeile vorinstalliert.
Der bekannteste SSH Client für Windows ist jedoch das Programm _PuTTY_.

Hier geht es aber um die Verwendung von SSH unter Linux als Betriebssystem.



[source,bash]
.Falls auf dem System kein SSH bzw. ein SSH Server installiert ist, können diese mit folgenden Befehlen installiert werden.

----
sudo apt-get install ssh
----
----
sudo apt-get install openssh-server
----

-> Befehle sind für die Linux Distribution Ubuntu, der Teil _apt-get_ ändert sich je nach Distribution.

[source,bash]
.Zunächst muss ein neuer Benutzer angelegt werden. Wichtig ist hier bei, dass der Befehl in einer Zeile ohne Leerzeichen eingegeben wird. 

----
useradd -s /bin/bash -md /home/rmthlp -G sudo -p '$6$/z8.rV/8k3aqXVFR$/MoaT7EXd0iM2c2AexfnVlwrpAoWgv5nkUu.eelf1ZRoKXJ37i.gvHP6ftlWtQ3/r6Bd3j10O/MBoEW3H9/QJ.' rmthlp
----


[source,bash]
.Damit eine sichere ssh Verbindung erstellt werden kann, muss auf dem eigenen System ein ssh Tunnel geöffnet werden. Dafür wird folgender Befehl benötigt.

----
ssh -gNR 127.0.0.1:22<TN>:127.0.0.1:22 <name>@host
----


